fix: added repos unit tests and fixed policy bugs
Legit-Labs/legitify pull request #71
Opened 2022-12-12 10:30 UTC by nadav-legit

#### What's being changed?
Added unit tests and fixed bugs

#### Check off the following:

- [X] This PR follows the CONTRIBUTION.md guidelines
- [X] I have self-reviewed my changes before submitting the PR

2022-12-12 11:30 UTC, noamd-legit requested changes

2022-12-12 11:30 UTC, noamd-legit commented on policies/github/repository.rego
> +   diff[yearIndex] > 0
will it work when diff_year == 0 and diff_month > 3?

2022-12-12 11:30 UTC, noamd-legit commented on policies/gitlab/repository.rego
> +    yearIndex := 0
see question above

2022-12-12 16:03 UTC, gal-legit approved these changes

2022-12-12 16:47 UTC, gal-legit approved these changes

2022-12-13 08:17 UTC, noamd-legit approved these changes

2022-12-13 09:14 UTC, merged